/**
 * ============================================================================
 * Backend Python Module & File Naming Normalizer
 * ============================================================================
 * 
 * Feature Description:
 * Implements server-side symbol-to-filename transformations and PEP 8 compliant
 * snake_case normalization for generated Python modules and test files. Guarantees
 * that all output files generated by the migration agent use underscores between
 * words rather than squished words or camelCase.
 * 
 * Use Cases:
 * 1. Deriving clean snake_case filenames for C++ classes, functions, and symbols
 *    (e.g., AnalyticHestonEngine -> analytic_heston_engine.py).
 * 2. Normalizing legacy QuantLib all-lowercase filenames (e.g., flatforward.cpp -> flat_forward.py).
 * 3. Enforcing that test files follow the mirrored directory structure with test_ prefixes.
 * ============================================================================
 */

import { logFunctionCall } from "./logger.js";

/**
 * Domain dictionary for splitting squished lowercase financial and algorithmic terms.
 */
const DOMAIN_SEGMENT_TERMS: string[] = [
  "analytic", "european", "heston", "bachelier", "black", "scholes", "calculator",
  "formula", "constant", "flat", "forward", "day", "counter", "counters", "actual",
  "fixed", "normal", "distribution", "distributions", "term", "structure", "structures",
  "discount", "curve", "curves", "yield", "cash", "flows", "flow", "monte", "carlo",
  "sobol", "linear", "algebra", "error", "function", "functions", "gaussian", "vanilla",
  "option", "options", "engine", "engines", "pricing", "process", "processes",
  "stochastic", "volatility", "surface", "cube", "matrix", "vector", "solver", "solvers",
  "pde", "finite", "difference", "tree", "lattice", "swap", "bond", "cap", "floor",
  "swaption", "barrier", "asian", "american", "integral", "quadrature", "interpolation",
  "spline", "cholesky", "decomposer", "generator", "profiler", "packer", "segment",
  "stream", "reader", "snappy", "encoder", "round", "trip", "quickstart", "pipeline",
  "portfolio", "multi", "asset", "jump", "diffusion", "bessel", "beta", "gamma",
  "legendre", "hermite", "hypergeometric", "hypergeom", "arena", "buffer", "pool",
  "lock", "free", "ring", "queue", "direct", "dma", "packet", "murmur", "hash",
  "bitmapped", "flag", "register", "compressed", "complementary", "erf", "erfc",
  "standard", "density", "abscissae", "roots", "orthogonal", "thomas", "eigen",
  "symmetric", "strassen", "tensor", "kronecker", "band", "banded", "svd", "qr",
  "lu", "pade", "exponential", "expm", "inv", "moro", "lanczos"
];

/**
 * Splits an all-lowercase squished string using known quantitative domain terms.
 *
 * @param str - All-lowercase string without separators (e.g. "analytichestonengine")
 * @returns Underscore-separated string (e.g. "analytic_heston_engine")
 */
export function splitCompoundLowercaseWords(str: string): string {
  if (!str || str.length < 4) return str;
  if (str.includes("_") || str.includes("-")) return str;

  const segments: string[] = [];
  let remaining = str;

  while (remaining.length > 0) {
    let matched = false;

    // Check numeric blocks (e.g. "365", "64")
    const numMatch = remaining.match(/^(\d+)/);
    if (numMatch) {
      segments.push(numMatch[1]);
      remaining = remaining.slice(numMatch[1].length);
      continue;
    }

    for (const term of DOMAIN_SEGMENT_TERMS) {
      if (remaining.startsWith(term)) {
        segments.push(term);
        remaining = remaining.slice(term.length);
        matched = true;
        break;
      }
    }

    if (!matched) {
      if (segments.length > 0 && remaining.length <= 3) {
        segments.push(remaining);
        remaining = "";
      } else {
        return str;
      }
    }
  }

  return segments.length > 1 ? segments.join("_") : str;
}

/**
 * Transforms a symbol or filename into standard PEP 8 snake_case with underscores.
 *
 * @param str - Input string (e.g. "AnalyticHestonEngine", "FlatForward", "daycounter.cpp")
 * @returns Lowercase string with underscore word boundaries (e.g. "analytic_heston_engine")
 */
export function toSnakeCase(str: string): string {
  if (!str) return "module";

  let clean = str
    .replace(/^.*[\\/]/, "")
    .replace(/\.(cpp|hpp|c|h|py|ts|tsx|js)$/i, "")
    .replace(/::/g, "_")
    .replace(/\./g, "_")
    .replace(/[^a-zA-Z0-9_]/g, "_");

  const hasUppercase = /[A-Z]/.test(clean);

  if (hasUppercase) {
    // Multi-letter uppercase acronyms followed by PascalCase: "QRDecomposer" -> "QR_Decomposer"
    clean = clean.replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2");
    // Lowercase / digit transition to uppercase: "AnalyticHestonEngine" -> "Analytic_Heston_Engine"
    clean = clean.replace(/([a-z0-9])([A-Z])/g, "$1_$2");
    // Letter-to-digit and digit-to-letter transitions: "Actual365Fixed" -> "Actual_365_Fixed"
    clean = clean.replace(/([a-zA-Z])(\d+)/g, "$1_$2");
    clean = clean.replace(/(\d+)([a-zA-Z])/g, "$1_$2");
  } else if (!clean.includes("_")) {
    clean = splitCompoundLowercaseWords(clean);
  }

  clean = clean
    .toLowerCase()
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");

  return clean || "module";
}

/**
 * Ensures any Python target or test file path uses underscore separators in its file name.
 *
 * @param filePath - Full file path (e.g. "torch_quantlib/pricingengines/analytichestonengine.py")
 * @param fallbackSymbol - Optional symbol used to preserve word casing if path is squished
 * @returns File path with underscored file name
 */
export function ensurePythonFilePathHasUnderscores(filePath: string, fallbackSymbol?: string): string {
  if (!filePath) return "module.py";

  if (filePath.endsWith("__init__.py") || filePath.endsWith("__main__.py") || filePath.endsWith("conftest.py")) {
    return filePath;
  }

  const parts = filePath.split("/");
  const rawFileName = parts.pop() || "module.py";
  const dir = parts.length > 0 ? parts.join("/") + "/" : "";

  let baseName = rawFileName.replace(/\.py$/i, "");
  const isTest = baseName.startsWith("test_");
  if (isTest) {
    baseName = baseName.slice(5);
  }

  let snakeBase = toSnakeCase(fallbackSymbol ? fallbackSymbol.replace(/^test_/i, "") : baseName);
  if (baseName.includes("_") && (!fallbackSymbol || fallbackSymbol.toLowerCase() === baseName)) {
    snakeBase = baseName.toLowerCase();
  }

  const finalFileName = isTest ? `test_${snakeBase}.py` : `${snakeBase}.py`;
  return `${dir}${finalFileName}`;
}
